hint "Will not work without a backpack.";
sleep 5;
hint "Adding medical supplies to your backpack now...";
sleep 5;
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_fieldDressing";
player addItemToBackpack "ACE_morphine";
player addItemToBackpack "ACE_morphine";
player addItemToBackpack "ACE_morphine";
player addItemToBackpack "ACE_morphine";
player addItemToBackpack "ACE_epinephrine";
player addItemToBackpack "ACE_epinephrine";
player addItemToBackpack "ACE_epinephrine";
player addItemToBackpack "ACE_epinephrine";
player addItemToBackpack "ACE_tourniquet";
player addItemToBackpack "ACE_tourniquet";
player addItemToBackpack "ACE_tourniquet";
player addItemToBackpack "ACE_tourniquet";