hint "This loadout costs $7000.";
sleep 5;
hint "Checking your balance...";
sleep 2;
if ([7000] call HG_fnc_hasEnoughMoney) then
{
	hint "You can afford this loadout...purchasing.";
	sleep 5;
	[7000,1] call HG_fnc_addOrSubCash;
	removeAllWeapons player;
	removeAllItems player;
	removeAllAssignedItems player;
	removeUniform player;
	removeVest player;
	removeBackpack player;
	removeHeadgear player;
	removeGoggles player;
	player forceAddUniform "ADFU_G3_MC";
	player addVest "milgp_v_marciras_grenadier_belt_mc";
	player addBackpack "B_AssaultPack_mcamo";
	player addItemToUniform "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToUniform "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToUniform "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToUniform "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "ACE_fieldDressing";
	player addItemToVest "rhsusf_ANPVS_15";
	player addItemToVest "ACE_tourniquet";
	player addItemToVest "ACE_tourniquet";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_morphine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_epinephrine";
	player addItemToVest "ACE_salineIV";
	player addItemToVest "ACE_salineIV";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToVest "rhs_mag_f1";
	player addItemToVest "rhs_mag_f1";
	player addItemToVest "rhs_mag_f1";
	player addItemToVest "rhs_mag_f1";
	player addItemToBackpack "ACE_fieldDressing";
	player addItemToBackpack "ACE_fieldDressing";
	player addItemToBackpack "ACE_fieldDressing";
	player addItemToBackpack "ACE_fieldDressing";
	player addItemToBackpack "ACE_salineIV";
	player addItemToBackpack "ACE_salineIV";
	player addItemToBackpack "ACE_morphine";
	player addItemToBackpack "ACE_morphine";
	player addItemToBackpack "ACE_EntrenchingTool";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addItemToBackpack "rhs_mag_30Rnd_556x45_M855A1_Stanag_Tracer_Red";
	player addWeapon "RH_M16A6";
	player addPrimaryWeaponItem "RH_ta01nsn_2D";
	player addPrimaryWeaponItem "bipod_02_F_blk";
	player addWeapon "RH_m9";
	player addWeapon "ACE_VectorDay";
	player linkItem "ItemMap";
	player linkItem "tf_anprc152";
	player linkItem "ItemCompass";
	player linkItem "tf_microdagr";
	player addHeadgear "milgp_h_opscore_06_goggles_RGR";
	player addGoggles "ADFU_f_face_shield_tactical_shemagh_khk";
}
else
{
	hint "You do not have enough money.";
};





